# Generated by Django 4.1.7 on 2023-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="todo_app.tag"
            ),
        ),
    ]
